const TodoActionTypes = {
  GET_TODOS_START: "GET_TODOS_START",
  GET_TODOS_SUCCESS: "GET_TODOS_SUCCESS",
  GET_TODOS_ERROR: "GET_TODOS_ERROR",

  ADD_TODOS_START: "ADD_TODOS_START",
  ADD_TODOS_SUCCESS: "ADD_TODOS_SUCCESS",
  ADD_TODOS_ERROR: "ADD_TODOS_ERROR",

  UPDATE_TODO_START: "UPDATE_TODO_START",
  UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
  UPDATE_TODO_ERROR: "UPDATE_TODO_ERROR",

  DELETE_TODO_START: "DELETE_TODO_START",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
  DELETE_TODO_ERROR: "DELETE_TODO_ERROR",

  GET_TODO_START: "GET_TODO_START",
  GET_TODO_SUCCESS: "GET_TODO_SUCCESS",
  GET_TODO_ERROR: "GET_TODO_ERROR"
};

export default TodoActionTypes;
